
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>

namespace facebook {
namespace react {

class ImageSequenceProps final : public ViewProps {
 public:
  ImageSequenceProps() = default;
  ImageSequenceProps(const PropsParserContext& context, const ImageSequenceProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  std::vector<std::string> images{};
  bool loop{true};
  int startFrameIndex{0};
  int framesPerSecond{24};
  int downsampleWidth{-1};
  int downsampleHeight{-1};
};

} // namespace react
} // namespace facebook
